# Generated by Django 5.0.2 on 2024-03-09 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('formula', models.CharField(max_length=2)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Compounds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('formula', models.CharField(max_length=255)),
                ('name', models.TextField()),
                ('elements', models.ManyToManyField(to='api.elements')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.groups')),
            ],
        ),
    ]
