# Generated by Django 5.0.2 on 2024-03-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compounds',
            new_name='Compound',
        ),
        migrations.RenameModel(
            old_name='Elements',
            new_name='Element',
        ),
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
    ]
